name: uhc
main: com.goatgoose.uhc.UHC
version: 0.1

commands:
  "team":
    description: Displays help for all /team commands
    usage: /team
    permission: uhc.help
  "team create":
    description: Creates a new team
    usage: /team create [Team Name] [Team Color]
    permission: uhc.team.create
  "team addPlayer":
    description: Adds a player to a team
    usage: /team addPlayer [Team] [Player]
    permission: uhc.team.addplayer
  "team setScore":
    description: Sets the score for the team
    usage: /team setScore [Team] [Score]
  "spectate":
    description: Toggles spectate for target player, defaults to self
    usage: /spectate [Player]
    permission: uhc.spectate
  "spreadTeams":
    description: Spreads teams evenly around the spawn with a given radius
    usage: /spreadTeams [Spread Radius]

permissions:
  uhc.help:
    description: Allows player to view plugin help files
    default: op
  uhc.team.create:
    description: Allows player to create a new team
    default: op
  uhc.team.addplayer:
    description: Allows player to add a player to a team
    default: op
  uhc.team.setscore:
    description: Allows player to set the score of a team
  uhc.spectate:
    description: Allows player to toggle spectate mode on target player
    default: op
  uhc.spreadteams:
    description: Allows player to use the spreadTeams command