name: uhc
main: com.goatgoose.uhc.UHC
version: 0.1

commands:
  "team":
    description: Displays help for all /team commands
    usage: /team
    permission: uhc.help
  "team create":
    description: Creates a new team
    usage: /team create [Team Name] [Team Color]
    permission: uhc.team.create
  "team addPlayer":
    description: Adds a new player to the specified team
    usage: /team addPlayer [Team] [Player]
    permission: uhc.team.addplayer
  "team removePlayer":
    description: Removes a player from any joined teams
    usage: /team removePlayer [Player]
    permission: uhc.team.removeplayer
  "team setScore":
    description: Replaces the team's score with the specified score
    usage: /team setScore [Team] [Score]
    permission: uhc.team.setscore
  "team setColor":
    description: Sets the team's color
    usage: /team setColor [Team] [Color]
    permission: uhc.team.setcolor
  "team list":
    description: Lists all created teams, or players in team if team is defined
    usage: /team list [Team]
    permission: uhc.team.list
  "spectate":
    description: Toggles spectate mode for the specified player
    usage: /spectate [Player]
    permission: uhc.spectate
  "spreadTeams":
    description: Spreads teams evenly around the spawn with a given radius
    usage: /spreadTeams [Spread Radius]
    permission: uhc.spreadteams
  "start":
    description: Starts the game
    usage: /start
    perimssion: uhc.start
  "freeze":
    description: Freezes all players without the uhc.freezebypass permission
    usage: /freeze
    permission: uhc.freeze
  "episodeInterval":
    description: Sets the interval (in minutes) to mark the end of an episode when recording, set to 0 to disable
    usage: /episodeInterval [Interval]
    permission: uhc.episodeinterval

permissions:
  uhc.help:
    description: Allows player to view plugin help files
    default: op
  uhc.team.create:
    description: Allows player permission to the /team create command
    default: op
  uhc.team.addplayer:
    description: Allows player permission to the /team addPlayer command
    default: op
  uhc.team.removeplayer:
    description: Allows player permission to the /team removePlayer command
    default: op
  uhc.team.setscore:
    description: Allows player permission to the /team setScore command
    defualt: op
  uhc.team.setcolor:
    description: Allows player permission to the /team setColor command
    defualt: true
  uhc.team.setothercolor:
    description: Allows player permission to specify a team other than their own when using the /team setColor command
    defualt: op
  uhc.team.list:
    description: Allows player permission to the /team list command
    defualt: true
  uhc.spectate:
    description: Allows player permission to the /spectate command
    default: op
  uhc.spreadteams:
    description: Allows player permission to the /spreadTeams command
    default: op
  uhc.start:
    description: Allows player permission to the /start command
    default: op
  uhc.freeze:
    description: Allows player permission to the /freeze command
    default: op
  uhc.freezebypass:
    description: Allows player to bypass the effects of the /freeze command
    defualt: op
  uhc.episodeinterval:
    description: Allows player permission to the /episodeInterval command
    default: true